/**
 * data.js
 * Static data – application types, their required fields and file requirements.
 */

/** @type {Array<{id:string, name:string, icon:string, description:string, fields:Array, files:Array}>} */
const APPLICATION_TYPES = [
  {
    id: 'new_business',
    name: 'Sanitary Permit – New Business',
    icon: '🏪',
    description: 'For newly established food, commercial, or public health establishments.',
    fields: [
      { name: 'business_name',    label: 'Business / Establishment Name', type: 'text',   required: true },
      { name: 'business_address', label: 'Business Address',              type: 'text',   required: true },
      { name: 'business_type',    label: 'Nature of Business',            type: 'select', required: true,
        options: ['Food Establishment','Bakery','Carinderia / Eatery','Restaurant','Grocery / Sari-sari Store',
                  'Beauty Salon / Barbershop','Spa / Massage Parlor','Clinic / Laboratory','Other'] },
      { name: 'owner_name',       label: 'Owner / Operator Name',         type: 'text',   required: true },
      { name: 'contact_number',   label: 'Contact Number',                type: 'tel',    required: true },
      { name: 'email_address',    label: 'Email Address',                 type: 'email',  required: false },
      { name: 'num_employees',    label: 'Number of Employees',           type: 'number', required: true },
    ],
    files: [
      { name: 'dti_sec',        label: 'DTI / SEC Registration',      required: true  },
      { name: 'barangay_clearance', label: 'Barangay Clearance',      required: true  },
      { name: 'floor_plan',     label: 'Floor Plan / Sketch',         required: true  },
      { name: 'water_analysis', label: 'Water Analysis Result',       required: false },
    ],
  },
  {
    id: 'renewal',
    name: 'Sanitary Permit – Renewal',
    icon: '🔄',
    description: 'Annual renewal of existing sanitary permit for operating establishments.',
    fields: [
      { name: 'prev_permit_no',   label: 'Previous Permit Number',        type: 'text',   required: true },
      { name: 'business_name',    label: 'Business / Establishment Name', type: 'text',   required: true },
      { name: 'business_address', label: 'Business Address',              type: 'text',   required: true },
      { name: 'owner_name',       label: 'Owner / Operator Name',         type: 'text',   required: true },
      { name: 'contact_number',   label: 'Contact Number',                type: 'tel',    required: true },
      { name: 'email_address',    label: 'Email Address',                 type: 'email',  required: false },
    ],
    files: [
      { name: 'prev_permit',      label: 'Previous Sanitary Permit',  required: true  },
      { name: 'barangay_clearance', label: 'Barangay Clearance',      required: true  },
      { name: 'water_analysis',   label: 'Water Analysis Result',     required: false },
    ],
  },
  {
    id: 'transfer_ownership',
    name: 'Transfer of Ownership',
    icon: '🔑',
    description: 'Change in ownership of an establishment with an existing sanitary permit.',
    fields: [
      { name: 'prev_permit_no',   label: 'Existing Permit Number',        type: 'text',   required: true },
      { name: 'business_name',    label: 'Business / Establishment Name', type: 'text',   required: true },
      { name: 'business_address', label: 'Business Address',              type: 'text',   required: true },
      { name: 'old_owner',        label: 'Previous Owner Name',           type: 'text',   required: true },
      { name: 'new_owner',        label: 'New Owner Name',                type: 'text',   required: true },
      { name: 'contact_number',   label: 'Contact Number',                type: 'tel',    required: true },
    ],
    files: [
      { name: 'deed_of_sale',     label: 'Deed of Sale / Transfer Document', required: true },
      { name: 'dti_new',          label: 'New DTI / SEC Registration',       required: true },
      { name: 'barangay_clearance', label: 'Barangay Clearance',             required: true },
    ],
  },
  {
    id: 'change_business_name',
    name: 'Change of Business Name',
    icon: '✏️',
    description: 'Update the registered business name on the sanitary permit.',
    fields: [
      { name: 'prev_permit_no',   label: 'Existing Permit Number',        type: 'text',   required: true },
      { name: 'old_business_name',label: 'Old Business Name',             type: 'text',   required: true },
      { name: 'new_business_name',label: 'New Business Name',             type: 'text',   required: true },
      { name: 'business_address', label: 'Business Address',              type: 'text',   required: true },
      { name: 'owner_name',       label: 'Owner / Operator Name',         type: 'text',   required: true },
      { name: 'contact_number',   label: 'Contact Number',                type: 'tel',    required: true },
    ],
    files: [
      { name: 'new_dti',          label: 'New DTI / Business Name Registration', required: true },
      { name: 'prev_permit',      label: 'Previous Sanitary Permit',            required: true },
    ],
  },
  {
    id: 'additional_activities',
    name: 'Additional / Expanded Activities',
    icon: '➕',
    description: 'Adding new activities or expanding services to an existing establishment.',
    fields: [
      { name: 'prev_permit_no',     label: 'Existing Permit Number',        type: 'text',     required: true },
      { name: 'business_name',      label: 'Business / Establishment Name', type: 'text',     required: true },
      { name: 'business_address',   label: 'Business Address',              type: 'text',     required: true },
      { name: 'owner_name',         label: 'Owner / Operator Name',         type: 'text',     required: true },
      { name: 'contact_number',     label: 'Contact Number',                type: 'tel',      required: true },
      { name: 'new_activities',     label: 'Additional Activities / Services', type: 'textarea', required: true },
    ],
    files: [
      { name: 'prev_permit',      label: 'Previous Sanitary Permit', required: true },
      { name: 'floor_plan',       label: 'Updated Floor Plan',       required: true },
    ],
  },
  {
    id: 'temporary_permit',
    name: 'Temporary Sanitary Permit',
    icon: '⏱️',
    description: 'Short-term permit for temporary food stalls, events, or seasonal operations.',
    fields: [
      { name: 'establishment_name', label: 'Stall / Establishment Name',  type: 'text',  required: true },
      { name: 'location',           label: 'Location / Venue',            type: 'text',  required: true },
      { name: 'event_name',         label: 'Event / Activity Name',       type: 'text',  required: false },
      { name: 'start_date',         label: 'Operation Start Date',        type: 'date',  required: true },
      { name: 'end_date',           label: 'Operation End Date',          type: 'date',  required: true },
      { name: 'owner_name',         label: 'Owner / Operator Name',       type: 'text',  required: true },
      { name: 'contact_number',     label: 'Contact Number',              type: 'tel',   required: true },
    ],
    files: [
      { name: 'barangay_clearance', label: 'Barangay Clearance',       required: true  },
      { name: 'event_permit',       label: 'Event / Venue Permit',     required: false },
    ],
  },
  {
    id: 'sanitary_clearance',
    name: 'Sanitary Clearance',
    icon: '📋',
    description: 'Certificate of compliance for non-food establishments or general businesses.',
    fields: [
      { name: 'establishment_name', label: 'Establishment Name', type: 'text',  required: true },
      { name: 'address',            label: 'Address',            type: 'text',  required: true },
      { name: 'purpose',            label: 'Purpose of Clearance', type: 'select', required: true,
        options: ['Business Permit Application','Loan / Financial Requirements','Property Transaction','Other'] },
      { name: 'owner_name',         label: 'Owner / Representative Name', type: 'text', required: true },
      { name: 'contact_number',     label: 'Contact Number',              type: 'tel',  required: true },
    ],
    files: [
      { name: 'barangay_clearance', label: 'Barangay Clearance',          required: true },
      { name: 'valid_id',           label: 'Valid Government ID',          required: true },
    ],
  },
  {
    id: 'health_certificate',
    name: 'Health Certificate',
    icon: '💊',
    description: 'Required for food handlers, health workers, and public service employees.',
    fields: [
      { name: 'full_name',    label: 'Full Name',              type: 'text',   required: true },
      { name: 'birthday',     label: 'Date of Birth',          type: 'date',   required: true },
      { name: 'address',      label: 'Home Address',           type: 'text',   required: true },
      { name: 'occupation',   label: 'Occupation / Position',  type: 'text',   required: true },
      { name: 'employer',     label: 'Employer / Establishment',type: 'text',  required: true },
      { name: 'contact_number', label: 'Contact Number',       type: 'tel',    required: true },
    ],
    files: [
      { name: 'chest_xray',   label: 'Chest X-Ray Result',           required: true  },
      { name: 'fecalysis',    label: 'Fecalysis / Stool Exam Result', required: true  },
      { name: 'valid_id',     label: 'Valid Government ID',           required: true  },
      { name: '2x2_photo',    label: '2×2 ID Photo',                  required: true  },
    ],
  },
  {
    id: 'food_handler_permit',
    name: "Food Handler's Permit",
    icon: '🍽️',
    description: "Permit for individuals handling, preparing, or serving food commercially.",
    fields: [
      { name: 'full_name',          label: 'Full Name',                    type: 'text',  required: true },
      { name: 'birthday',           label: 'Date of Birth',                type: 'date',  required: true },
      { name: 'address',            label: 'Home Address',                 type: 'text',  required: true },
      { name: 'employer',           label: 'Employer / Establishment',     type: 'text',  required: true },
      { name: 'employer_address',   label: 'Employer Address',             type: 'text',  required: true },
      { name: 'contact_number',     label: 'Contact Number',               type: 'tel',   required: true },
    ],
    files: [
      { name: 'health_certificate', label: 'Current Health Certificate', required: true  },
      { name: 'chest_xray',         label: 'Chest X-Ray Result',         required: true  },
      { name: 'fecalysis',          label: 'Fecalysis Result',           required: true  },
      { name: 'valid_id',           label: 'Valid Government ID',         required: true  },
    ],
  },
  {
    id: 'water_refilling_station',
    name: 'Water Refilling Station Permit',
    icon: '💧',
    description: 'Sanitary permit specific to water refilling and purification stations.',
    fields: [
      { name: 'station_name',    label: 'Station Name',              type: 'text',   required: true },
      { name: 'station_address', label: 'Station Address',           type: 'text',   required: true },
      { name: 'owner_name',      label: 'Owner / Operator Name',     type: 'text',   required: true },
      { name: 'contact_number',  label: 'Contact Number',            type: 'tel',    required: true },
      { name: 'email_address',   label: 'Email Address',             type: 'email',  required: false },
      { name: 'water_source',    label: 'Water Source',              type: 'select', required: true,
        options: ['Deep Well','Municipal Water','Spring Water','Surface Water'] },
      { name: 'treatment_method',label: 'Treatment / Purification Method', type: 'text', required: true },
    ],
    files: [
      { name: 'water_analysis',  label: 'Bacteriological & Physical Water Analysis', required: true },
      { name: 'dti',             label: 'DTI / Business Registration',               required: true },
      { name: 'floor_plan',      label: 'Floor Plan showing equipment layout',       required: true },
      { name: 'barangay_clearance', label: 'Barangay Clearance',                     required: true },
    ],
  },
  {
    id: 'swimming_pool_spa',
    name: 'Swimming Pool / Spa Permit',
    icon: '🏊',
    description: 'Sanitary inspection and permit for swimming pools, spas, and bathhouses.',
    fields: [
      { name: 'establishment_name', label: 'Establishment Name',          type: 'text',   required: true },
      { name: 'establishment_address', label: 'Establishment Address',    type: 'text',   required: true },
      { name: 'owner_name',         label: 'Owner / Operator Name',       type: 'text',   required: true },
      { name: 'contact_number',     label: 'Contact Number',              type: 'tel',    required: true },
      { name: 'pool_capacity',      label: 'Pool Capacity (persons)',      type: 'number', required: true },
      { name: 'water_treatment',    label: 'Water Treatment System Used', type: 'text',   required: true },
    ],
    files: [
      { name: 'water_analysis',     label: 'Pool Water Analysis Result',  required: true },
      { name: 'dti',                label: 'DTI / Business Registration', required: true },
      { name: 'floor_plan',         label: 'Establishment Floor Plan',    required: true },
      { name: 'barangay_clearance', label: 'Barangay Clearance',          required: true },
    ],
  },
];

export { APPLICATION_TYPES };
